### ISSUE TITLE
Point linguist syntax at this repo?

### ISSUE THREAD

**Issue by macintacos** [nefrob/vscode-just#30] opened 2024-08-26 22:20 UTC
As of https://github.com/casey/just/pull/2034, it seems like this repository is the "official" repository for VSCode users. The last repository ([skellock/vscode-just](https://github.com/skellock/vscode-just)) was the pointer for the syntaxes for GitHub to use when rendering `just` code blocks, so it feels reasonable to request that that be updated to point to this repository instead, assuming that each project is using TextMate grammars (based on the README, I think that's the case).

For context, the initial PR to use https://github.com/skellock/vscode-just for rendering Github code blocks was made here: https://github.com/github-linguist/linguist/pull/6086. I have no experience with this system, but that PR should probably cover most of what you need to change for the Linguist maintainers to be satisfied. There's also [this part of their CONTRIBUTING.md documentation](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar), but I haven't tested how "easy" it would be to change, as they claim.

**Comment by nefrob** [comment] 2024-08-28 15:29
Closing as a duplicate of: https://github.com/nefrob/vscode-just/issues/15. A PR has been opened in linguist here: https://github.com/github-linguist/linguist/pull/6985.

**Closed by nefrob** 2024-08-28 15:29 UTC
